baseURL = "https://zhangxingong.fun/"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true
languageCode = "zh-Hans"
title = "Ethan的博客"
theme = "maupassant"
googleAnalytics = "G-GNMC997HW5"  # UA-XXXXXXXX-X/G-XXXXXXXXXX G-GNMC997HW5

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

summaryLength = 80 ##默认70

enableEmoji = true ## 允许使用 Emoji 表情，建议 true
enableRobotsTXT = true ## 允许爬虫抓取到搜索引擎，建议 true

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "Ethan"
 
[params]
  author = "Ethan"
  subtitle = "专注于Java、Elisp(Emacs)、移动互联网、项目管理、软件架构"
  keywords = "Emacs,Go语言(golang),java语言,博客建站,博主,DevOps,成长笔记,知识问答,elisp,互联网,想法,心流,认知,觉醒,GTD,项目管理,数据分析,python,软件架构,公众号,小程序,人工智能,AI,chatGPT"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Emacs、Python、微服务、项目管理、抖音分析、软件架构、人工智能AI、ChatGPT、等"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "沪ICP备080293639号"
  fancybox = true
  memosAuthorization = "eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiZXRoYW4iLCJpc3MiOiJtZW1vcyIsInN1YiI6Ijc5IiwiYXVkIjpbInVzZXIuYWNjZXNzLXRva2VuIl0sImlhdCI6MTcwMjYwOTI1MH0.a0IDD1Vl90buVjacwmKLgxQxcU_8YRyiuaIT4DcBI00"
  cdnJsSite = "cdn.bootcdn.net" # 默认：cdnjs.cloudflare.com
  baiduAnalytics = "b4bf6ed501b47a5473e135e2b6e481f0"  # 百度统计
  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file , 'snow.js'
  customJS = ['totop.js?v=0.0.0', 'lately.min.js', 'waterfall.min.js', 'imgStatus.min.js', 'view-image.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "Ethan的博客"
  name = "Ethan"
  url = "https://gcore.jsdelivr.net/gh/zhangxingong/blog@main/static/img/qrcode_for_weixin.jpg"
  ## url = "https://zhangxingong.github.io/"

[[params.links]]
  title = "大佬开发的免注册无需翻墙的人工智能"
  name = "Chat GPT"
  url = "https://zhonghuipro.com/"
  
[[params.links]]
  title = "廖雪峰的网站"
  name = "廖雪峰"
  url = "https://www.liaoxuefeng.com/"  


[[params.links]]
  title = "小小的幸福"
  name = "小小的幸福"
  url = "http://www.vimer.cn/"  


[[params.links]]
  title = "阮一峰"
  name = "阮一峰"
  url = "https://www.ruanyifeng.com/"


[[params.links]]
  title = "金步国"
  name = "金步国"
  url = "http://www.jinbuguo.com/"  
  

[[params.links]]
  title = "骏马金龙的博客"
  name = "一位非科班出身的运维"
  url = "https://www.junmajinlong.com/"

## 侧边栏广告位
[[params.ads]]
  title = "【腾讯云】推广者专属福利，新客户无门槛领取总价值高达2860元代金券，每种代金券限量500张，先到先得。"
  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1040&cps_key=c7c743b60bfe454f8c8672e0aed0de92&from=console"
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345x200--2953d058277cb63c6b1cd127285163335cd6751e.jpg"
[[params.ads]]
  title = "【腾讯云】腾讯云图，像PPT一样简单的数据可视化工具。5元搞定数据可视化，模板丰富，拖拖拽拽就能做出好看的可视化大屏。"
  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1046&cps_key=c7c743b60bfe454f8c8672e0aed0de92&from=console"
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345x200-89eeba55a2f49008e686e1a51e14bfe79f63af13.png"
[[params.ads]] 
  title = "【腾讯云】视频通信爆款 9.9 元起， 提供电商、教育、社交娱乐等多行业多场景的一站式解决方案，最快 1 天布局火爆赛道【腾讯云】云服务器、云数据库、COS、CDN、短信等云产品特惠热卖中"
  url = "https://cloud.tencent.com/act/cps/redirect?redirect=2446&cps_key=c7c743b60bfe454f8c8672e0aed0de92&from=console"
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/upload/nodir/345X200-9ae456f58874df499adf7c331c02cb0fed12b81d.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "zhangxingong/blog" ##换成自己得
  issueTerm = "pathname"
  label = "发言"
  theme = "github-light"
## 配置 waline 评论系统,教程参考 https://waline.js.org/
[params.waline]
  enable = false
  placeholder = "说点什么吧..."
  serverURL = "Your waline serverURL" #换成你的serverURL
## 配置 valine 评论系统,教程参考 https://valine.js.org/
[params.valine]
  enable = true
  appId = "Nx7WyTsont7tPeEf0aEHz79V-gzGzoHsz"
  appKey = "mMhhHs4sZh5gRNUWtaUieNIl" #换成你的serverURL  
## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮


## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "ideas"
    name = "碎碎念"
    url = "/ideas/"
    weight = 4
    

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
  

[params.image_cdn]
    enable = true
    Host = "https://gcore.jsdelivr.net/gh/zhangxingong/blog@main/static"
    ## "https://cdn.jsdelivr.net/gh/zhangxingong/zhangxingong.github.io"

[params.sequenceDiagrams]
    enable = true
    options = ""            # default: "{theme: 'simple'}"
    #sequenceDiagrams
    #enable: true

[params.flowchartDiagrams]
  enable = true
  options = ""
  #graphviz:
  #enable: true
  #flowchartDiagrams: 
  #enable: true

  
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    lineNos = true
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true  
      unsafe = true
     

  
  
